@RPSSL.Identity_HostAddress = https://localhost:7106

### Register a new user
POST {{RPSSL.Identity_HostAddress}}/api/user/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "SecurePassword123!"
}

### Login with the new user
POST {{RPSSL.Identity_HostAddress}}/api/user/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "SecurePassword123!"
}
